title: Welcome to Flexton
description: Flexton is a responsive and ultra-minimal theme for Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "flexton.netlify.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    Emma Nader
author-image:   1.jpg
author-job:     Finance and Data Analytics Student
author-email:   emma.nader25@gmail.com
about-author:   High-achieving Finance student with a sub-major in Data Analytics (WAM 84.8, GPA 6.5),
passionate about applying data-driven insights to solve complex business problems. Skilled in Excel,
Tableau, and Power BI with experience in financial transactions, client service, and process
improvement. Recognised for analytical thinking, adaptability, and clear communication, developed
through academic excellence, work experience, and competitive case competitions. Seeking to
contribute technical expertise, client service skills, and commercial awareness to a leading financial
institution.

# Social settings
social-twitter:   artemsheludko_
social-facebook:
social-github:    artemsheludko
social-pinterest: artemsheludko
social-instagram: artemsheludko_
social-youtube:
social-vk:   
social-linkedin:

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
